- name: "Create directory for {{ role_name }} files"
  file:
    path: "{{ docker_dir }}/{{ role_name }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true

- name: "Copy {{ role_name }} files"
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_dir }}/{{ role_name }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
  with_items:
    - docker-compose.yml
    - fileConfig.yml
    - traefik.yml
  become: true

- name: "Run {{ role_name }}"
  community.docker.docker_compose:
    project_src: "{{ docker_dir }}/{{ role_name }}"
    state: present
  become: true
  ignore_errors: true